"""Synthesize — compose the report body, with a citation-grounding guardrail.

Prose is generated by the synthesis tier (Opus); every inline citation must
resolve to a real reference number, or the guardrail strips it. This is the
safety spine of a medical product: no claim may carry an ungrounded citation.
"""
from __future__ import annotations

import re
from typing import Any

from .. import contract
from ..llm import LLMClient, ModelTier
from .models import Extraction, GradeOutcome, short_authors

SYNTH_SYSTEM = (
    "You are a medical research-synthesis writer. Write clear, hedged prose grounded "
    "in the supplied evidence. Cite sources only with {{cite:N}} tokens, using ONLY "
    "the reference numbers listed under CITE_REFS. Never invent a citation number. "
    "This is not clinical advice."
)

_CITE_TOKEN = re.compile(r"\{\{cite:(\d+)\}\}")


def ground_prose(
    html: str, citations: list[dict[str, Any]], valid_numbers: set[int]
) -> tuple[str, list[dict[str, Any]], int]:
    """Drop any citation (entry or {{cite:N}} token) that doesn't resolve to a
    real reference. Returns (clean_html, kept_citations, dropped_count)."""
    kept = [c for c in citations if c["number"] in valid_numbers]
    kept_numbers = {c["number"] for c in kept}
    dropped_entries = len(citations) - len(kept)

    dropped_tokens = 0

    def _replace(match: re.Match[str]) -> str:
        nonlocal dropped_tokens
        n = int(match.group(1))
        if n in kept_numbers:
            return match.group(0)
        dropped_tokens += 1
        return ""

    clean = _CITE_TOKEN.sub(_replace, html)
    return clean, kept, dropped_entries + dropped_tokens


def _ref_type(design: str, is_preprint: bool) -> str:
    if design == "meta-analysis":
        return "meta-analysis"
    if design == "review":
        return "review"
    if is_preprint:
        return "preprint"
    return "journal-article"


def build_references(
    included: list[dict[str, Any]], extractions: list[Extraction]
) -> list[dict[str, Any]]:
    by_id = {p["id"]: p for p in included}
    refs: list[dict[str, Any]] = []
    for e in extractions:
        p = by_id.get(e.paper_id, {})
        venue = p.get("venue", {}) or {}
        refs.append(
            {
                "id": e.ref_id,
                "number": e.number,
                "type": _ref_type(e.study_design, bool(p.get("isPreprint"))),
                "authors": [a.get("name", "") for a in p.get("authors", []) if a.get("name")] or ["Unknown"],
                "year": int(p.get("year") or 0),
                "title": p.get("title", "(untitled)"),
                "venue": venue.get("name", "Unknown venue"),
                "doi": (p.get("externalIds", {}) or {}).get("doi"),
                "url": p.get("url"),
                "openAccess": bool(p.get("isOpenAccess")),
                "citationCount": int(p.get("citationCount") or 0),
            }
        )
    return refs


def _evidence_digest(extractions: list[Extraction], limit: int = 6) -> str:
    lines = []
    for e in extractions[:limit]:
        lines.append(f"- [{e.number}] {e.study_design}, n={e.sample_size}: {e.outcome} ({e.effect_direction}); stance={e.stance}")
    return "\n".join(lines)


def _prose(
    llm: LLMClient,
    topic: str,
    section: str,
    support: list[Extraction],
    valid_numbers: set[int],
) -> tuple[dict[str, Any], int]:
    cite_refs = [e.number for e in support]
    prompt = (
        f"TOPIC: {topic}\n"
        f"SECTION: {section}\n"
        f"CITE_REFS: {', '.join(str(n) for n in cite_refs)}\n\n"
        f"EVIDENCE:\n{_evidence_digest(support)}\n\n"
        f"Write one short paragraph for the '{section}' section."
    )
    html = llm.text(ModelTier.SYNTH, SYNTH_SYSTEM, prompt)
    citations = [
        contract.citation(e.ref_id, e.number, e.stance, e.quote[:160] or e.outcome)
        for e in support
    ]
    clean, kept, dropped = ground_prose(html, citations, valid_numbers)
    return contract.prose(clean, kept), dropped


def _key_papers(included: list[dict[str, Any]], extractions: list[Extraction]) -> dict[str, Any]:
    by_id = {p["id"]: p for p in included}
    ranked = sorted(extractions, key=lambda e: int(by_id.get(e.paper_id, {}).get("citationCount") or 0), reverse=True)
    items = []
    for e in ranked[:3]:
        p = by_id.get(e.paper_id, {})
        items.append(
            {
                "citationCount": int(p.get("citationCount") or 0),
                "title": p.get("title", "(untitled)"),
                "authors": short_authors(p),
                "year": int(p.get("year") or 0),
                "venue": (p.get("venue", {}) or {}).get("name", "Unknown venue"),
                "summary": e.quote[:200] or f"{e.outcome} ({e.effect_direction}).",
                "refId": e.ref_id,
            }
        )
    return contract.key_papers(items, caption="Figure 3 — Anchor papers in the corpus.")


def _reading_time(blocks: list[dict[str, Any]]) -> int:
    words = 0
    for b in blocks:
        if b.get("type") in ("prose", "tldr"):
            words += len(re.sub(r"<[^>]+>", " ", b.get("html", "")).split())
    return max(3, round(words / 200) + 3)


def synthesize(
    topic: str,
    included: list[dict[str, Any]],
    extractions: list[Extraction],
    g: GradeOutcome,
    screen_funnel: list[dict[str, Any]],
    llm: LLMClient,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], int, dict[str, int]]:
    references = build_references(included, extractions)
    valid_numbers = {r["number"] for r in references}
    dropped_total = 0

    def prose(section: str, support: list[Extraction]) -> dict[str, Any]:
        nonlocal dropped_total
        block, dropped = _prose(llm, topic, section, support, valid_numbers)
        dropped_total += dropped
        return block

    yes_like = [e for e in extractions if e.stance in ("yes", "possibly")]
    rigorous = [e for e in extractions if e.study_design in ("rct", "meta-analysis", "review")]

    tldr_html = llm.text(
        ModelTier.SYNTH,
        SYNTH_SYSTEM,
        f"TOPIC: {topic}\nSECTION: TL;DR\nWrite a two-sentence plain-language summary. No citations.",
    )

    blocks: list[dict[str, Any]] = [
        contract.tldr(tldr_html),
        contract.heading(2, "Introduction", "1"),
        prose("Introduction", extractions[:2]),
        contract.consensus_meter(
            f"Does the evidence support: {topic}?",
            g.contributing_studies,
            g.meter_buckets,
            caption="Figure 1 — Distribution of study conclusions across the included corpus.",
        ),
        contract.heading(2, "Methods", "2"),
        prose("Methods", []),
        contract.funnel_block(screen_funnel, caption="Figure 2 — Search and screening funnel."),
        contract.heading(2, "Results", "3"),
        contract.heading(3, "Key papers", "3.1"),
        prose("Key papers", rigorous[:3] or extractions[:3]),
        _key_papers(included, extractions),
        contract.heading(3, "Effect directions", "3.2"),
        prose("Effect directions", yes_like[:3]),
        contract.evidence_matrix(
            g.matrix_rows, caption="Figure 4 — Effect directions and their evidence signal."
        ),
        contract.heading(3, "Research timeline", "3.3"),
        prose("Research timeline", extractions[:2]),
        contract.timeline(
            g.timeline_axis[0],
            g.timeline_axis[1],
            g.timeline_points,
            caption="Figure 5 — Publications over time; larger markers indicate more citations.",
        ),
        contract.heading(2, "Discussion", "4"),
        prose("Discussion", extractions[: min(4, len(extractions))]),
        contract.claims(
            g.claims_rows, caption="Figure 6 — Key claims and the strength of their evidence."
        ),
        contract.heading(2, "Conclusion", "5"),
        prose("Conclusion", rigorous[:2] or extractions[:2]),
        contract.heading(3, "Open research questions"),
        contract.open_questions(g.open_questions),
    ]

    grounding = {"citationsKept": sum(len(b.get("citations", [])) for b in blocks if b.get("type") == "prose"), "dropped": dropped_total}
    return blocks, references, _reading_time(blocks), grounding
