/* Runtime configuration, sourced from environment with sensible defaults. */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
/** Repo root, from server/src/config.ts → ../../ */
const repoRoot = join(here, '..', '..');

/** Parse a "cmd arg arg" string into argv; falls back to the default worker. */
function parseBrainCmd(): string[] {
  const raw = process.env.BRAIN_CMD;
  if (raw && raw.trim()) return raw.trim().split(/\s+/);
  return ['python3', join(repoRoot, 'synthesis', 'run.py')];
}

export const config = {
  port: Number(process.env.PORT ?? 8787),
  host: process.env.HOST ?? '0.0.0.0',
  basePath: '/api/v1',
  repoRoot,
  /** Static token the mock issues and accepts. */
  staticToken: process.env.MOCK_TOKEN ?? 'mock-token-corpus',
  /** When set, the PubMed provider hits live NCBI E-utilities. */
  useLivePubmed: process.env.USE_LIVE_PUBMED === '1',
  /** Per-event delay (ms) for the simulated SSE pipeline (fixture path). */
  streamStepMs: Number(process.env.STREAM_STEP_MS ?? 220),
  /** When set, reports are generated by the Python synthesis worker (the Brain)
   *  instead of the fixture; the worker speaks the same SSE event contract. */
  useBrain: process.env.USE_BRAIN === '1',
  /** Worker command (argv). Default: `python3 synthesis/run.py`. */
  brainCmd: parseBrainCmd(),
  /** Candidate corpus size pulled from the aggregator before screening. */
  brainCandidates: Number(process.env.BRAIN_CANDIDATES ?? 40),
  /** Per-report token budget passed to the worker (0 / unset = unbounded). */
  brainMaxTokens: Number(process.env.CORPUS_BRAIN_MAX_TOKENS ?? 0) || undefined,
} as const;
