/* Runtime configuration, sourced from environment with sensible defaults. */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
/** Repo root, from server/src/config.ts → ../../ */
const repoRoot = join(here, '..', '..');

/** Parse a comma/space-separated env list into trimmed, lowercased ids. */
function parseList(v: string | undefined): string[] {
  return (v ?? '')
    .split(/[,\s]+/)
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
}

/** Parse a "cmd arg arg" string into argv; falls back to the default worker. */
function parseBrainCmd(): string[] {
  const raw = process.env.BRAIN_CMD;
  if (raw && raw.trim()) return raw.trim().split(/\s+/);
  return ['python3', join(repoRoot, 'synthesis', 'run.py')];
}

export const config = {
  port: Number(process.env.PORT ?? 8787),
  host: process.env.HOST ?? '0.0.0.0',
  basePath: '/api/v1',
  repoRoot,
  /** Static token the mock issues and accepts. */
  staticToken: process.env.MOCK_TOKEN ?? 'mock-token-corpus',
  /** When set, the PubMed provider hits live NCBI E-utilities. */
  useLivePubmed: process.env.USE_LIVE_PUBMED === '1',
  /** Active search providers, e.g. "openalex,semantic-scholar,biorxiv". When
   *  empty, falls back to PubMed (if USE_LIVE_PUBMED) or the mock fixtures. */
  providers: parseList(process.env.CORPUS_PROVIDERS),
  /** Active enrichers, e.g. "sjr". Run over the merged result set. */
  enrichers: parseList(process.env.CORPUS_ENRICHERS),
  /** Per-event delay (ms) for the simulated SSE pipeline (fixture path). */
  streamStepMs: Number(process.env.STREAM_STEP_MS ?? 220),
  /** When set, reports are generated by the Python synthesis worker (the Brain)
   *  instead of the fixture; the worker speaks the same SSE event contract. */
  useBrain: process.env.USE_BRAIN === '1',
  /** Worker command (argv). Default: `python3 synthesis/run.py`. */
  brainCmd: parseBrainCmd(),
  /** Candidate corpus size pulled from the aggregator before screening. */
  brainCandidates: Number(process.env.BRAIN_CANDIDATES ?? 40),
  /** Per-report token budget passed to the worker (0 / unset = unbounded). */
  brainMaxTokens: Number(process.env.CORPUS_BRAIN_MAX_TOKENS ?? 0) || undefined,

  /** Job queue driver: 'memory' (default, in-process) or 'bullmq' (Redis). */
  queueDriver: process.env.QUEUE_DRIVER === 'bullmq' ? ('bullmq' as const) : ('memory' as const),
  /** Concurrent report-generation jobs the worker pool runs. */
  queueConcurrency: Number(process.env.QUEUE_CONCURRENCY ?? 4),
  /** Total attempts per job before it is marked failed. */
  queueDefaultMaxAttempts: Number(process.env.QUEUE_MAX_ATTEMPTS ?? 3),
  /** Redis connection for the bullmq driver. */
  redisUrl: process.env.REDIS_URL ?? 'redis://localhost:6379',

  /** Recompute cadence for `cadence: weekly` reports (default 7 days). */
  weeklyCadenceMs: Number(process.env.WEEKLY_CADENCE_MS ?? 7 * 24 * 60 * 60 * 1000),
  /** How often the scheduler checks for due recomputes. */
  schedulerTickMs: Number(process.env.SCHEDULER_TICK_MS ?? 60 * 60 * 1000),
  /** Opt in to the background recompute scheduler (off in tests/e2e). */
  enableScheduler: process.env.ENABLE_SCHEDULER === '1',
} as const;
